services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "7654:443"
    restart: always
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "2345:3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maxence/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maxence/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge
