services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always
  
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  
  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    
  redis:
    container_name: redis
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/
    restart: always

  # ftp:
  #   container_name: ftp
  #   build: requirements/bonus/ftp
  #   ports:
  #     - "21:21"
  #     - "30000-30100:30000-30100"
  #   depends_on:
  #     - wordpress
  #   env_file:
  #     - .env
  #   environment:
  #     - FTP_DIR=/home
  #   restart: always
  #   volumes:
  #     - wordpress:/wp
  adminer:
    container_name: adminer
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maxence/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maxence/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge