services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always
  
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  
  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    
  redis:
    container_name: redis
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/
    restart: always

  ftp:
    container_name: ftp
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  adminer:
    container_name: adminer
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "600:80"
    restart: always

  uptimekuma:
    container_name: uptimekuma
    image: inception-uptimekuma
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirements/bonus/UptimeKuma
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    restart: always
  websites:
    container_name: websites
    networks:
      - inception
    build:
      context: requirements/bonus/websites
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maxence/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maxence/data/mariadb
  uptime-kuma-data:  # <-- Assure-toi que cette ligne est bien présente !
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maxence/data/uptimekuma
networks:
  inception:
    name: inception
    driver: bridge