CREATE DATABASE IF NOT EXISTS ${SQL_DATABASE};
CREATE DATABASE IF NOT EXISTS ${SQL_DATABASE_UK};


CREATE USER IF NOT EXISTS '${SQL_USER}'@'%' IDENTIFIED BY '${SQL_PASSWORD}';
CREATE USER IF NOT EXISTS '${SQL_wp_user}'@'wordpress.inception' IDENTIFIED BY '${SQL_wp_password}';

GRANT ALL PRIVILEGES ON ${SQL_DATABASE_UK}.* TO '${SQL_USER}'@'%';
GRANT ALL PRIVILEGES ON ${SQL_DATABASE}.* TO '${SQL_USER}'@'%';
GRANT ALL PRIVILEGES ON ${SQL_DATABASE}.* TO '${SQL_wp_user}'@'wordpress.inception';

ALTER USER 'root'@'localhost' IDENTIFIED BY '${SQL_ROOT_PASSWORD}';

